apiVersion: v1
kind: Service
metadata:
    name: {{ include "helmapp1.fullname" . }}
    labels:
        app: {{ include "helmapp1.name" . }}
spec:
    selector:
      app: {{ include "helmapp1.name" . }}
    type: {{ .Values.service.type }}
    ports:
        - port: {{ .Values.service.port }}
          nodePort: {{ .Values.service.nodePort }}
